continuumVersion=3.1.0

allureVersion=2.35.5
aspectJVersion=1.9.25
apacheCommonsLangVersion=3.20.0
apacheCommonsTextVersion=1.15.0
commonsIoVersion=2.22.0
igniteVersion=2.18.0
jCacheApiVersion=1.1.1
jreleaserVersion=1.26.0
lombokPluginVersion=9.5.0
nettyVersion=4.2.18.Final
otelBomVersion=1.65.0
otelInstrumentationBomVersion=2.31.1
springBootVersion=4.1.1
springDependencyManagementVersion=1.1.7
vertxVersion=5.1.8
vertxStompLiteVersion=6.0.0
